# Generated by Django 2.2.1 on 2019-10-12 04:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 4, 3, 21, 354008, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='media',
            field=models.ImageField(blank=True, upload_to='complaints_image'),
        ),
    ]
