# Generated by Django 2.2.1 on 2019-10-12 05:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('grievance_app', '0002_auto_20191012_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 12, 5, 7, 4, 579931, tzinfo=utc)),
        ),
    ]
